const defaultTours = [
  {
    _id: 1,
    name: "เคซี แกรนด์ รีสอร์ท",
    summary: "แพ็คเกจที่พัก 3 วัน 2 คืน (จองขั้นต่ำ 2 ท่าน)",
    startDates: new Date(),
    food: "4 มื้อ",
    duration: "3 วัน 2 คืน",
    maxGroupSize: 10,
    price: 3690,
    imageCover: "http://base.kohchangclub.com/thtimages/swimming-pool-02.jpg",
  },
  {
    _id: 2,
    name: "คชา รีสอร์ท",
    summary: "แพ็คเกจที่พัก 3 วัน 2 คืน (จองขั้นต่ำ 2 ท่าน)",
    startDates: new Date(),
    food: "4 มื้อ",
    duration: "3 วัน 2 คืน",
    maxGroupSize: 10,
    price: 3190,
    imageCover:
      "http://base.kohchangclub.com/thtimages/Kacha%20Koh%20Chang%20Beach%20Pool%20012_640x427.jpg",
  },
  {
    _id: 3,
    name: "เซ็นทารา ทรอปิคาน่า",
    summary: "แพ็คเกจที่พัก 3 วัน 2 คืน (จองขั้นต่ำ 2 ท่าน)",
    startDates: new Date(),
    food: "4 มื้อ",
    duration: "3 วัน 2 คืน",
    maxGroupSize: 10,
    price: 3890,
    imageCover: "http://base.kohchangclub.com/thtimages/swimming-pool-02.jpg",
  },
  {
    _id: 4,
    name: "เคซี แกรนด์ รีสอร์ท",
    summary: "แพ็คเกจที่พัก 3 วัน 2 คืน (จองขั้นต่ำ 2 ท่าน)",
    startDates: new Date(),
    food: "4 มื้อ",
    duration: "3 วัน 2 คืน",
    maxGroupSize: 10,
    price: 3690,
    imageCover:
      "http://base.kohchangclub.com/thtimages/Kacha%20Koh%20Chang%20Beach%20Pool%20012_640x427.jpg",
  },
  {
    _id: 5,
    name: "คชา รีสอร์ท",
    summary: "แพ็คเกจที่พัก 3 วัน 2 คืน (จองขั้นต่ำ 2 ท่าน)",
    startDates: new Date(),
    food: "4 มื้อ",
    duration: "3 วัน 2 คืน",
    maxGroupSize: 10,
    price: 3190,
    imageCover:
      "http://base.kohchangclub.com/thtimages/ckc_duplexaerial-view-01_640x427.jpg",
  },
  {
    _id: 6,
    name: "เซ็นทารา ทรอปิคาน่า",
    summary: "แพ็คเกจที่พัก 3 วัน 2 คืน (จองขั้นต่ำ 2 ท่าน)",
    startDates: new Date(),
    food: "4 มื้อ",
    duration: "3 วัน 2 คืน",
    maxGroupSize: 10,
    price: 3890,
    imageCover: "http://base.kohchangclub.com/thtimages/swimming-pool-02.jpg",
  },
];

export default defaultTours;
